#!/bin/bash

# install packages with pacman
sudo pacman -S $(cat packages_to_install)

# Install python modules
sudo pip install $(cat python_packages)

# stow all config files
stow $(ls -d */ | awk -F/ '{print $1}')

# install flatpacks that specially need to be isolated from rest of the system
flatpak install flathub $(cat flatpacks_to_install)

# Configure vim plugins
curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
vim +'PlugInstall'

# add packer to neovim
git clone --depth 1 https://github.com/wbthomason/packer.nvim\
 ~/.local/share/nvim/site/pack/packer/start/packer.nvim

cp dotfiles/nvim ./config/nvim -r

# Config github cli
gh auth login

# clone passwords from github
git clone https://github.com/ChrisW-priv/password_store.git 

# clone repo to customise grub
git clone https://github.com/stuarthayhurst/argon-grub-theme.git
# execute install to customise grub
sudo ./argon-grub-theme/install.sh --install --resolution custom --background Grey

# base rules for firewall
sudo ufw limit 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw enable
